apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-consumer
  name: service-consumer
spec:
  ports:
    - name: http
      port: 18083
      protocol: TCP
      targetPort: 18083
  selector:
    app: service-consumer
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-consumer
  template:
    metadata:
      labels:
        app: service-consumer
    spec:
      containers:
        - name: service-consumer
          image: 578986218/service-consumer:latest
          ports:
            - containerPort: 18083
