apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-provider
  name: service-provider
spec:
  ports:
    - name: http
      port: 18082
      protocol: TCP
      targetPort: 18082
  selector:
    app: service-provider
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-provider
  template:
    metadata:
      labels:
        app: service-provider
    spec:
      containers:
        - name: service-provider
          image: 578986218/service-provider:latest
          ports:
            - containerPort: 18082
