apiVersion: v1
kind: Service
metadata:
  labels:
    app: nacos-config
  name: nacos-config
spec:
  ports:
    - name: http
      port: 18084
      protocol: TCP
      targetPort: 18084
  selector:
    app: nacos-config
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos-config
  template:
    metadata:
      labels:
        app: nacos-config
    spec:
      containers:
        - name: nacos-config
          image: 578986218/nacos-config:latest
          ports:
            - containerPort: 18084
